const data = {
  headers: [
    {
      id: "id",
      text: "#",
    },
    {
      id: "studyid",
      text: "Study ID",
    },
    {
      id: "sex",
      text: "Sex",
    },
    {
      id: "age",
      text: "Age Scanned",
    },
    {
      id: "height",
      text: "Height",
    },
    {
      id: "weight_lbs",
      text: "Weight (Lbs)",
    },
    {
      id: "sport",
      text: "Sport",
    },
    {
      id: "control_concussed",
      text: "Control",
    },
    {
      id: "date_of_testing",
      text: "Scan Date",
      sortType: "date",
    },
  ],
  items: [
    {
      studyid: "HU_BC_01",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "135",
      id: 1,
      age: 18,
      control_concussed: "Concussed",
      height: "5'7\"",
      date_of_testing: "1/24/20",
    },
    {
      studyid: "HU_BC_02",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "135",
      id: 2,
      age: 18,
      control_concussed: "Concussed",
      height: "5'7\"",
      date_of_testing: "1/17/20",
    },
    {
      studyid: "HU_BC_03",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "135",
      id: 3,
      age: 18,
      control_concussed: "Concussed",
      height: "5'6\"",
      date_of_testing: "1/29/20",
    },
    {
      studyid: "HU_BC_04",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 4,
      age: "",
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "1/31/20",
    },
    {
      studyid: "HU_Conc_01",
      sex: "Male",
      sport: "Football",
      weight_lbs: "260",
      id: 5,
      age: 20,
      control_concussed: "Control",
      height: "6'3\"",
      date_of_testing: "11/5/15",
    },
    {
      studyid: "HU_Conc_01",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 6,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/3/15",
    },
    {
      studyid: "HU_Conc_01",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 7,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/4/16",
    },
    {
      studyid: "HU_Conc_02",
      sex: "Male",
      sport: "Football",
      weight_lbs: "260",
      id: 8,
      age: 20,
      control_concussed: "Control",
      height: "6'3\"",
      date_of_testing: "11/11/15",
    },
    {
      studyid: "HU_Conc_02",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 9,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/4/15",
    },
    {
      studyid: "HU_Conc_02",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 10,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/5/16",
    },
    {
      studyid: "HU_Conc_03",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "135",
      id: 11,
      age: 19,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "3/3/16",
    },
    {
      studyid: "HU_Conc_03",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 12,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/9/16",
    },
    {
      studyid: "HU_Conc_03",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 13,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "6/13/16",
    },
    {
      studyid: "HU_Conc_04",
      sex: "Female",
      sport: "Crew",
      weight_lbs: "170",
      id: 14,
      age: 19,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "4/8/16",
    },
    {
      studyid: "HU_Conc_04",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 15,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/10/16",
    },
    {
      studyid: "HU_Conc_04",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 16,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "8/16/16",
    },
    {
      studyid: "HU_Conc_05",
      sex: "Male",
      sport: "Football",
      weight_lbs: "285",
      id: 17,
      age: 21,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "4/13/16",
    },
    {
      studyid: "HU_Conc_05",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 18,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/9/16",
    },
    {
      studyid: "HU_Conc_05",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 19,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "8/31/16",
    },
    {
      studyid: "HU_Conc_06",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "150",
      id: 20,
      age: 19,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "4/16/16",
    },
    {
      studyid: "HU_Conc_06",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 21,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/12/16",
    },
    {
      studyid: "HU_Conc_07",
      sex: "Male",
      sport: "Football",
      weight_lbs: "195",
      id: 22,
      age: 19,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "9/6/16",
    },
    {
      studyid: "HU_Conc_07",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 23,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/7/16",
    },
    {
      studyid: "HU_Conc_07",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 24,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/2/17",
    },
    {
      studyid: "HU_Conc_08",
      sex: "Female",
      sport: "Field Hockey",
      weight_lbs: "140",
      id: 25,
      age: 20,
      control_concussed: "Control",
      height: "5'8\"",
      date_of_testing: "9/12/16",
    },
    {
      studyid: "HU_Conc_08",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 26,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/7/16",
    },
    {
      studyid: "HU_Conc_08",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 27,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/8/16",
    },
    {
      studyid: "HU_Conc_09",
      sex: "Female",
      sport: "Basketball",
      weight_lbs: "150",
      id: 28,
      age: 19,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "9/14/16",
    },
    {
      studyid: "HU_Conc_09",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 29,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/10/16",
    },
    {
      studyid: "HU_Conc_10",
      sex: "Male",
      sport: "Football",
      weight_lbs: "200",
      id: 30,
      age: 20,
      control_concussed: "Control",
      height: "5'10\"",
      date_of_testing: "9/19/16",
    },
    {
      studyid: "HU_Conc_10",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 31,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/10/16",
    },
    {
      studyid: "HU_Conc_10",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 32,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/12/16",
    },
    {
      studyid: "HU_Conc_11",
      sex: "Female",
      sport: "Tennis",
      weight_lbs: "125",
      id: 33,
      age: 18,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "10/3/16",
    },
    {
      studyid: "HU_Conc_12",
      sex: "Male",
      sport: "Football",
      weight_lbs: "215",
      id: 34,
      age: 19,
      control_concussed: "Control",
      height: "6'3\"",
      date_of_testing: "10/3/16",
    },
    {
      studyid: "HU_Conc_12",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 35,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/19/16",
    },
    {
      studyid: "HU_Conc_12",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 36,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/31/17",
    },
    {
      studyid: "HU_Conc_13",
      sex: "Male",
      sport: "Football",
      weight_lbs: "172",
      id: 37,
      age: 20,
      control_concussed: "Control",
      height: "6'1\"",
      date_of_testing: "10/10/16",
    },
    {
      studyid: "HU_Conc_13",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 38,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/14/16",
    },
    {
      studyid: "HU_Conc_13",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 39,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/31/17",
    },
    {
      studyid: "HU_Conc_14",
      sex: "Male",
      sport: "Football",
      weight_lbs: "218",
      id: 40,
      age: 19,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "10/10/16",
    },
    {
      studyid: "HU_Conc_15",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "182",
      id: 41,
      age: 18,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "10/10/16",
    },
    {
      studyid: "HU_Conc_15",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 42,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/16/16",
    },
    {
      studyid: "HU_Conc_15",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 43,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/31/17",
    },
    {
      studyid: "HU_Conc_16",
      sex: "Female",
      sport: "Track and Field",
      weight_lbs: "175",
      id: 44,
      age: 19,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "10/10/16",
    },
    {
      studyid: "HU_Conc_16",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 45,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/7/16",
    },
    {
      studyid: "HU_Conc_16",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 46,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/25/17",
    },
    {
      studyid: "HU_Conc_17",
      sex: "Female",
      sport: "Field Hockey",
      weight_lbs: "133",
      id: 47,
      age: 19,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "10/17/16",
    },
    {
      studyid: "HU_Conc_18",
      sex: "Male",
      sport: "Football",
      weight_lbs: "235",
      id: 48,
      age: 20,
      control_concussed: "Control",
      height: "6'3\"",
      date_of_testing: "10/19/16",
    },
    {
      studyid: "HU_Conc_18",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 49,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/17/16",
    },
    {
      studyid: "HU_Conc_18",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 50,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/24/17",
    },
    {
      studyid: "HU_Conc_19",
      sex: "Female",
      sport: "Field Hockey",
      weight_lbs: "133",
      id: 51,
      age: 18,
      control_concussed: "Control",
      height: "5'4\"",
      date_of_testing: "10/31/16",
    },
    {
      studyid: "HU_Conc_19",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 52,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/5/16",
    },
    {
      studyid: "HU_Conc_20",
      sex: "Male",
      sport: "Soccer",
      weight_lbs: "188",
      id: 53,
      age: 20,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "10/31/16",
    },
    {
      studyid: "HU_Conc_21",
      sex: "Male",
      sport: "Wrestling",
      weight_lbs: "157",
      id: 54,
      age: 22,
      control_concussed: "Control",
      height: "5'8\"",
      date_of_testing: "11/2/16",
    },
    {
      studyid: "HU_Conc_21",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 55,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/8/16",
    },
    {
      studyid: "HU_Conc_21",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 56,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/2/17",
    },
    {
      studyid: "HU_Conc_22",
      sex: "Female",
      sport: "Volleyball",
      weight_lbs: "130",
      id: 57,
      age: 18,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "11/7/16",
    },
    {
      studyid: "HU_Conc_22",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 58,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/8/16",
    },
    {
      studyid: "HU_Conc_22",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 59,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/1/17",
    },
    {
      studyid: "HU_Conc_23",
      sex: "Male",
      sport: "Football",
      weight_lbs: "265",
      id: 60,
      age: 19,
      control_concussed: "Control",
      height: "6'7\"",
      date_of_testing: "11/7/16",
    },
    {
      studyid: "HU_Conc_23",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 61,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/7/16",
    },
    {
      studyid: "HU_Conc_23",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 62,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/31/17",
    },
    {
      studyid: "HU_Conc_24",
      sex: "Female",
      sport: "Ice Hockey",
      weight_lbs: "140",
      id: 63,
      age: 21,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "12/5/16",
    },
    {
      studyid: "HU_Conc_24",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 64,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/12/17",
    },
    {
      studyid: "HU_Conc_25",
      sex: "Female",
      sport: "Crew",
      weight_lbs: "120",
      id: 65,
      age: 20,
      control_concussed: "Control",
      height: "5'2\"",
      date_of_testing: "2/1/17",
    },
    {
      studyid: "HU_Conc_25",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 66,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/6/17",
    },
    {
      studyid: "HU_Conc_28",
      sex: "Female",
      sport: "Field Hockey",
      weight_lbs: "130",
      id: 67,
      age: 20,
      control_concussed: "Control",
      height: "5'3\"",
      date_of_testing: "8/21/17",
    },
    {
      studyid: "HU_Conc_29",
      sex: "Male",
      sport: "Sailing",
      weight_lbs: "145",
      id: 68,
      age: "",
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "",
    },
    {
      studyid: "HU_Conc_29",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 69,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/10/17",
    },
    {
      studyid: "HU_Conc_29",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 70,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/2/18",
    },
    {
      studyid: "HU_Conc_30",
      sex: "Male",
      sport: "Football",
      weight_lbs: "235",
      id: 71,
      age: 21,
      control_concussed: "Control",
      height: "6'3\"",
      date_of_testing: "9/11/17",
    },
    {
      studyid: "HU_Conc_30",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 72,
      age: "",
      control_concussed: "",
      height: "",
      date_of_testing: "11/8/17",
    },
    {
      studyid: "HU_Conc_30",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 73,
      age: "",
      control_concussed: "",
      height: "",
      date_of_testing: "3/2/18",
    },
    {
      studyid: "HU_Conc_31",
      sex: "Female",
      sport: "Sailing",
      weight_lbs: "154",
      id: 74,
      age: 19,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "9/15/17",
    },
    {
      studyid: "HU_Conc_31",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 75,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/15/17",
    },
    {
      studyid: "HU_Conc_31",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 76,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/28/18",
    },
    {
      studyid: "HU_Conc_32",
      sex: "Male",
      sport: "Sailing",
      weight_lbs: "185",
      id: 77,
      age: 20,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "9/18/17",
    },
    {
      studyid: "HU_Conc_33",
      sex: "Female",
      sport: "Basketball",
      weight_lbs: "130",
      id: 78,
      age: 19,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "9/18/17",
    },
    {
      studyid: "HU_Conc_33",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 79,
      age: "",
      control_concussed: "",
      height: "",
      date_of_testing: "",
    },
    {
      studyid: "HU_Conc_34",
      sex: "Male",
      sport: "Football",
      weight_lbs: "185",
      id: 80,
      age: 19,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "9/20/17",
    },
    {
      studyid: "HU_Conc_34",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 81,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/20/17",
    },
    {
      studyid: "HU_Conc_34",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 82,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/6/18",
    },
    {
      studyid: "HU_Conc_35",
      sex: "Male",
      sport: "Lacrosse",
      weight_lbs: "185",
      id: 83,
      age: 19,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "10/2/17",
    },
    {
      studyid: "HU_Conc_36",
      sex: "Female",
      sport: "Lacrosse",
      weight_lbs: "150",
      id: 84,
      age: 20,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "10/2/17",
    },
    {
      studyid: "HU_Conc_36",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 85,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/27/17",
    },
    {
      studyid: "HU_Conc_36",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 86,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/27/18",
    },
    {
      studyid: "HU_Conc_37",
      sex: "Male",
      sport: "Baseball",
      weight_lbs: "178",
      id: 87,
      age: 20,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "10/11/17",
    },
    {
      studyid: "HU_Conc_37",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 88,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/4/17",
    },
    {
      studyid: "HU_Conc_37",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 89,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/28/18",
    },
    {
      studyid: "HU_Conc_38",
      sex: "Male",
      sport: "Football",
      weight_lbs: "",
      id: 90,
      age: 21,
      control_concussed: "Control",
      height: "6'3\"",
      date_of_testing: "10/13/17",
    },
    {
      studyid: "HU_Conc_39",
      sex: "Male",
      sport: "Football",
      weight_lbs: "293",
      id: 91,
      age: 22,
      control_concussed: "Control",
      height: "6'4\"",
      date_of_testing: "10/23/17",
    },
    {
      studyid: "HU_Conc_39",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 92,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/30/17",
    },
    {
      studyid: "HU_Conc_40",
      sex: "Female",
      sport: "Volleyball",
      weight_lbs: "132",
      id: 93,
      age: 18,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "10/25/17",
    },
    {
      studyid: "HU_Conc_41",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "125",
      id: 94,
      age: 22,
      control_concussed: "Control",
      height: "5'8\"",
      date_of_testing: "10/25/17",
    },
    {
      studyid: "HU_Conc_42",
      sex: "Male",
      sport: "Football",
      weight_lbs: "265",
      id: 95,
      age: 21,
      control_concussed: "Control",
      height: "6'4\"",
      date_of_testing: "10/31/17",
    },
    {
      studyid: "HU_Conc_43",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "125",
      id: 96,
      age: 21,
      control_concussed: "Control",
      height: "5'5\"",
      date_of_testing: "11/6/17",
    },
    {
      studyid: "HU_Conc_43",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 97,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/26/18",
    },
    {
      studyid: "HU_Conc_43",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 98,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/25/18",
    },
    {
      studyid: "HU_Conc_44",
      sex: "Male",
      sport: "Soccer",
      weight_lbs: "128",
      id: 99,
      age: 22,
      control_concussed: "Concussed",
      height: "5'7\"",
      date_of_testing: "11/14/17",
    },
    {
      studyid: "HU_Conc_44",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 100,
      age: "",
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "2/6/18",
    },
    {
      studyid: "HU_Conc_44",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 101,
      age: "",
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "5/1/18",
    },
    {
      studyid: "HU_Conc_45",
      sex: "Male",
      sport: "Football",
      weight_lbs: "200",
      id: 102,
      age: 20,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "11/13/17",
    },
    {
      studyid: "HU_Conc_45",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 103,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/2/18",
    },
    {
      studyid: "HU_Conc_46",
      sex: "Female",
      sport: "Ice Hockey",
      weight_lbs: "145",
      id: 104,
      age: 18,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "11/20/17",
    },
    {
      studyid: "HU_Conc_47",
      sex: "Female",
      sport: "Volleyball",
      weight_lbs: "130",
      id: 105,
      age: 19,
      control_concussed: "Concussed",
      height: "5'8\"",
      date_of_testing: "12/5/17",
    },
    {
      studyid: "HU_Conc_48",
      sex: "Male",
      sport: "Basketball",
      weight_lbs: "210",
      id: 106,
      age: 19,
      control_concussed: "Control",
      height: "6'4\"",
      date_of_testing: "12/4/17",
    },
    {
      studyid: "HU_Conc_48",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 107,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/30/18",
    },
    {
      studyid: "HU_Conc_48",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 108,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/8/18",
    },
    {
      studyid: "HU_Conc_49",
      sex: "Male",
      sport: "Baseball",
      weight_lbs: "190",
      id: 109,
      age: 21,
      control_concussed: "Concussed",
      height: "5'11\"",
      date_of_testing: "4/6/18",
    },
    {
      studyid: "HU_Conc_49",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 110,
      age: "",
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "5/10/18",
    },
    {
      studyid: "HU_Conc_50",
      sex: "Male",
      sport: "Football",
      weight_lbs: "178",
      id: 111,
      age: 20,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "1/29/18",
    },
    {
      studyid: "HU_Conc_50",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 112,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/6/18",
    },
    {
      studyid: "HU_Conc_51",
      sex: "Female",
      sport: "Skiing",
      weight_lbs: "146",
      id: 113,
      age: 19,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "2/1/18",
    },
    {
      studyid: "HU_Conc_51",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 114,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/2/18",
    },
    {
      studyid: "HU_Conc_52",
      sex: "Female",
      sport: "Sailing",
      weight_lbs: "128",
      id: 115,
      age: 21,
      control_concussed: "Control",
      height: "5'2\"",
      date_of_testing: "3/20/18",
    },
    {
      studyid: "HU_Conc_52",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 116,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/16/18",
    },
    {
      studyid: "HU_Conc_53",
      sex: "Female",
      sport: "Softball",
      weight_lbs: "175",
      id: 117,
      age: 21,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "3/19/18",
    },
    {
      studyid: "HU_Conc_53",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 118,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/8/18",
    },
    {
      studyid: "HU_Conc_53",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 119,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "9/20/18",
    },
    {
      studyid: "HU_Conc_54",
      sex: "Male",
      sport: "Basketball",
      weight_lbs: "223",
      id: 120,
      age: 21,
      control_concussed: "Concussed",
      height: "6'6\"",
      date_of_testing: "3/20/18",
    },
    {
      studyid: "HU_Conc_54",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 121,
      age: "",
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "5/3/18",
    },
    {
      studyid: "HU_Conc_55",
      sex: "Female",
      sport: "Softball",
      weight_lbs: "155",
      id: 122,
      age: 21,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "3/27/18",
    },
    {
      studyid: "HU_Conc_55",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 123,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/3/18",
    },
    {
      studyid: "HU_Conc_55",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 124,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/19/18",
    },
    {
      studyid: "HU_Conc_56",
      sex: "Female",
      sport: "Football",
      weight_lbs: "198",
      id: 125,
      age: 20,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "4/9/18",
    },
    {
      studyid: "HU_Conc_57",
      sex: "Female",
      sport: "Softball",
      weight_lbs: "165",
      id: 126,
      age: 20,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "4/17/18",
    },
    {
      studyid: "HU_Conc_57",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 127,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "7/20/18",
    },
    {
      studyid: "HU_Conc_57",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 128,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/19/18",
    },
    {
      studyid: "HU_Conc_58",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "135",
      id: 129,
      age: 18,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "8/20/18",
    },
    {
      studyid: "HU_Conc_58",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 130,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/15/18",
    },
    {
      studyid: "HU_Conc_59",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "140",
      id: 131,
      age: 18,
      control_concussed: "Control",
      height: "5'8\"",
      date_of_testing: "8/20/18",
    },
    {
      studyid: "HU_Conc_59",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 132,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/13/18",
    },
    {
      studyid: "HU_Conc_59",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 133,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/28/19",
    },
    {
      studyid: "HU_Conc_60",
      sex: "Male",
      sport: "Football",
      weight_lbs: "246",
      id: 134,
      age: 20,
      control_concussed: "Control",
      height: "6'8\"",
      date_of_testing: "8/27/18",
    },
    {
      studyid: "HU_Conc_61",
      sex: "Male",
      sport: "Football",
      weight_lbs: "",
      id: 135,
      age: 19,
      control_concussed: "Control",
      height: "",
      date_of_testing: "8/27/18",
    },
    {
      studyid: "HU_Conc_62",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "",
      id: 136,
      age: 21,
      control_concussed: "Control",
      height: "5'5\"",
      date_of_testing: "9/20/18",
    },
    {
      studyid: "HU_Conc_62",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 137,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/14/18",
    },
    {
      studyid: "HU_Conc_62",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 138,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/21/19",
    },
    {
      studyid: "HU_Conc_63",
      sex: "Male",
      sport: "Football",
      weight_lbs: "240",
      id: 139,
      age: 18,
      control_concussed: "Control",
      height: "6'4\"",
      date_of_testing: "10/1/18",
    },
    {
      studyid: "HU_Conc_63",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 140,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/2/19",
    },
    {
      studyid: "HU_Conc_64",
      sex: "Male",
      sport: "Football",
      weight_lbs: "225",
      id: 141,
      age: 0,
      control_concussed: "Control",
      height: "6'1\"",
      date_of_testing: "10/1/18",
    },
    {
      studyid: "HU_Conc_65",
      sex: "Female",
      sport: "Field Hockey",
      weight_lbs: "168",
      id: 142,
      age: 22,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "10/5/18",
    },
    {
      studyid: "HU_Conc_65",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 143,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "11/30/18",
    },
    {
      studyid: "HU_Conc_65",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 144,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/29/19",
    },
    {
      studyid: "HU_Conc_66",
      sex: "Female",
      sport: "Ice Hockey",
      weight_lbs: "160",
      id: 145,
      age: 20,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "10/10/18",
    },
    {
      studyid: "HU_Conc_66",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 146,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/13/18",
    },
    {
      studyid: "HU_Conc_66",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 147,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/17/19",
    },
    {
      studyid: "HU_Conc_67",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "180",
      id: 148,
      age: 20,
      control_concussed: "Control",
      height: "5'10\"",
      date_of_testing: "10/15/18",
    },
    {
      studyid: "HU_Conc_68",
      sex: "Female",
      sport: "Volleyball",
      weight_lbs: "120",
      id: 149,
      age: 20,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "10/15/18",
    },
    {
      studyid: "HU_Conc_68",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 150,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/13/18",
    },
    {
      studyid: "HU_Conc_68",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 151,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/11/19",
    },
    {
      studyid: "HU_Conc_69",
      sex: "Male",
      sport: "Water Polo",
      weight_lbs: "225",
      id: 152,
      age: 22,
      control_concussed: "Control",
      height: "6'4\"",
      date_of_testing: "10/15/18",
    },
    {
      studyid: "HU_Conc_69",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 153,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/17/18",
    },
    {
      studyid: "HU_Conc_69",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 154,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/17/19",
    },
    {
      studyid: "HU_Conc_70",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "203",
      id: 155,
      age: 20,
      control_concussed: "Control",
      height: "5'5\"",
      date_of_testing: "10/17/18",
    },
    {
      studyid: "HU_Conc_70",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 156,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/19/18",
    },
    {
      studyid: "HU_Conc_70",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 157,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "4/17/19",
    },
    {
      studyid: "HU_Conc_71",
      sex: "Male",
      sport: "Volleyball",
      weight_lbs: "200",
      id: 158,
      age: 20,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "10/22/18",
    },
    {
      studyid: "HU_Conc_72",
      sex: "Male",
      sport: "Wrestling",
      weight_lbs: "137",
      id: 159,
      age: 22,
      control_concussed: "Control",
      height: "5'5\"",
      date_of_testing: "10/29/18",
    },
    {
      studyid: "HU_Conc_73",
      sex: "Female",
      sport: "Skiing",
      weight_lbs: "163",
      id: 160,
      age: 21,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "10/31/18",
    },
    {
      studyid: "HU_Conc_74",
      sex: "Male",
      sport: "Football",
      weight_lbs: "240",
      id: 161,
      age: 19,
      control_concussed: "Control",
      height: "6'4\"",
      date_of_testing: "10/31/18",
    },
    {
      studyid: "HU_Conc_75",
      sex: "Male",
      sport: "Wrestling",
      weight_lbs: "125",
      id: 162,
      age: 20,
      control_concussed: "Control",
      height: "5'4\"",
      date_of_testing: "11/5/18",
    },
    {
      studyid: "HU_Conc_75",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 163,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/7/19",
    },
    {
      studyid: "HU_Conc_76",
      sex: "Male",
      sport: "Football",
      weight_lbs: "252",
      id: 164,
      age: 18,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "11/6/18",
    },
    {
      studyid: "HU_Conc_77",
      sex: "Male",
      sport: "Football",
      weight_lbs: "205",
      id: 165,
      age: 19,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "11/5/18",
    },
    {
      studyid: "HU_Conc_77",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 166,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/7/19",
    },
    {
      studyid: "HU_Conc_77",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 167,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/8/19",
    },
    {
      studyid: "HU_Conc_78",
      sex: "Male",
      sport: "Ice Hockey",
      weight_lbs: "195",
      id: 168,
      age: 21,
      control_concussed: "Control",
      height: "6'1\"",
      date_of_testing: "11/12/18",
    },
    {
      studyid: "HU_Conc_79",
      sex: "Female",
      sport: "Basketball",
      weight_lbs: "",
      id: 169,
      age: 22,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "11/13/18",
    },
    {
      studyid: "HU_Conc_79",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 170,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/12/19",
    },
    {
      studyid: "HU_Conc_79",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 171,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/13/19",
    },
    {
      studyid: "HU_Conc_80",
      sex: "Male",
      sport: "Wrestling",
      weight_lbs: "184",
      id: 172,
      age: 19,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "11/19/18",
    },
    {
      studyid: "HU_Conc_80",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 173,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "3/4/19",
    },
    {
      studyid: "HU_Conc_81",
      sex: "Male",
      sport: "Baseball",
      weight_lbs: "171",
      id: 174,
      age: 22,
      control_concussed: "Control",
      height: "6'1\"",
      date_of_testing: "12/3/18",
    },
    {
      studyid: "HU_Conc_82",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "145",
      id: 175,
      age: 18,
      control_concussed: "Control",
      height: "5'5\"",
      date_of_testing: "2/12/19",
    },
    {
      studyid: "HU_Conc_83",
      sex: "Female",
      sport: "Soccer",
      weight_lbs: "180",
      id: 176,
      age: 21,
      control_concussed: "Concussed",
      height: "5'11\"",
      date_of_testing: "2/22/19",
    },
    {
      studyid: "HU_Conc_83",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 177,
      age: "",
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "4/25/19",
    },
    {
      studyid: "HU_Conc_84",
      sex: "Male",
      sport: "Baseball",
      weight_lbs: "180",
      id: 178,
      age: 21,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "2/25/19",
    },
    {
      studyid: "HU_Conc_84",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 179,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "5/2/19",
    },
    {
      studyid: "HU_Conc_85",
      sex: "Female",
      sport: "Water Polo",
      weight_lbs: "152",
      id: 180,
      age: 19,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "3/4/19",
    },
    {
      studyid: "HU_Conc_86",
      sex: "Female",
      sport: "Basketball",
      weight_lbs: "165",
      id: 181,
      age: 19,
      control_concussed: "Control",
      height: "5'11\"",
      date_of_testing: "3/4/19",
    },
    {
      studyid: "HU_Conc_86",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 182,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/2/19",
    },
    {
      studyid: "HU_Conc_87",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "155",
      id: 183,
      age: 21,
      control_concussed: "Control",
      height: "5'4\"",
      date_of_testing: "4/1/19",
    },
    {
      studyid: "HU_Conc_87",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 184,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "9/20/19",
    },
    {
      studyid: "HU_Conc_88",
      sex: "Male",
      sport: "Baseball",
      weight_lbs: "215",
      id: 185,
      age: 21,
      control_concussed: "Control",
      height: "6'4\"",
      date_of_testing: "4/17/19",
    },
    {
      studyid: "HU_Conc_89",
      sex: "Male",
      sport: "Lacrosse",
      weight_lbs: "200",
      id: 186,
      age: 19,
      control_concussed: "Control",
      height: "6'2\"",
      date_of_testing: "4/17/19",
    },
    {
      studyid: "HU_Conc_90",
      sex: "Male",
      sport: "Baseball",
      weight_lbs: "195",
      id: 187,
      age: 20,
      control_concussed: "Control",
      height: "6'0\"",
      date_of_testing: "4/29/19",
    },
    {
      studyid: "HU_Conc_90",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 188,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/8/19",
    },
    {
      studyid: "HU_Conc_91",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "165",
      id: 189,
      age: 18,
      control_concussed: "Control",
      height: "5'8\"",
      date_of_testing: "9/10/19",
    },
    {
      studyid: "HU_Conc_91",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 190,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/6/19",
    },
    {
      studyid: "HU_Conc_92",
      sex: "Male",
      sport: "Water Polo",
      weight_lbs: "165",
      id: 191,
      age: 18,
      control_concussed: "Control",
      height: "6'0\"",
      date_of_testing: "9/11/19",
    },
    {
      studyid: "HU_Conc_92",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 192,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "1/24/20",
    },
    {
      studyid: "HU_Conc_93",
      sex: "Male",
      sport: "Sailing",
      weight_lbs: "140",
      id: 193,
      age: 18,
      control_concussed: "Control",
      height: "5'9\"",
      date_of_testing: "9/23/19",
    },
    {
      studyid: "HU_Conc_94",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "",
      id: 194,
      age: 24,
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "10/25/19",
    },
    {
      studyid: "HU_Conc_94",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 195,
      age: "",
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "3/11/20",
    },
    {
      studyid: "HU_Conc_95",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "140",
      id: 196,
      age: 20,
      control_concussed: "Concussed",
      height: "5'8\"",
      date_of_testing: "11/1/19",
    },
    {
      studyid: "HU_Conc_96",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "190",
      id: 197,
      age: 19,
      control_concussed: "Concussed",
      height: "5'8\"",
      date_of_testing: "10/23/19",
    },
    {
      studyid: "HU_Conc_97",
      sex: "Male",
      sport: "Crew",
      weight_lbs: "",
      id: 198,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/7/19",
    },
    {
      studyid: "HU_Conc_98",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "",
      id: 199,
      age: 23,
      control_concussed: "Concussed",
      height: "",
      date_of_testing: "10/25/19",
    },
    {
      studyid: "HU_Conc_98",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 200,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/18/20",
    },
    {
      studyid: "HU_Conc_100",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "160",
      id: 201,
      age: 21,
      control_concussed: "Control",
      height: "5'5\"",
      date_of_testing: "10/14/19",
    },
    {
      studyid: "HU_Conc_101",
      sex: "Male",
      sport: "Soccer",
      weight_lbs: "200",
      id: 202,
      age: 19,
      control_concussed: "Control",
      height: "6'1\"",
      date_of_testing: "10/14/19",
    },
    {
      studyid: "HU_Conc_102",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "195",
      id: 203,
      age: 20,
      control_concussed: "Concussed",
      height: "5'10\"",
      date_of_testing: "11/6/19",
    },
    {
      studyid: "HU_Conc_103",
      sex: "",
      sport: "Swimming",
      weight_lbs: "150",
      id: 204,
      age: 20,
      control_concussed: "Control",
      height: "5'10\"",
      date_of_testing: "10/18/19",
    },
    {
      studyid: "HU_Conc_103",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 205,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "12/9/19",
    },
    {
      studyid: "HU_Conc_104",
      sex: "",
      sport: "Sailing",
      weight_lbs: "155",
      id: 206,
      age: 18,
      control_concussed: "Control",
      height: "5'10\"",
      date_of_testing: "10/18/19",
    },
    {
      studyid: "HU_Conc_105",
      sex: "Male",
      sport: "",
      weight_lbs: "",
      id: 207,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/21/19",
    },
    {
      studyid: "HU_Conc_106",
      sex: "Female",
      sport: "",
      weight_lbs: "",
      id: 208,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "10/21/19",
    },
    {
      studyid: "HU_Conc_107",
      sex: "Male",
      sport: "Lacrosse",
      weight_lbs: "185",
      id: 209,
      age: 20,
      control_concussed: "Control",
      height: "5'10\"",
      date_of_testing: "11/6/19",
    },
    {
      studyid: "HU_Conc_108",
      sex: "Female",
      sport: "Rugby",
      weight_lbs: "120",
      id: 210,
      age: 20,
      control_concussed: "Control",
      height: "5'5\"",
      date_of_testing: "11/18/19",
    },
    {
      studyid: "HU_Conc_108",
      sex: "",
      sport: "",
      weight_lbs: "",
      id: 211,
      age: "",
      control_concussed: "Control",
      height: "",
      date_of_testing: "2/18/20",
    },
    {
      studyid: "HU_Conc_109",
      sex: "Female",
      sport: "Ice Hockey",
      weight_lbs: "140",
      id: 212,
      age: 21,
      control_concussed: "Control",
      height: "5'8\"",
      date_of_testing: "11/18/19",
    },
    {
      studyid: "HU_Conc_110",
      sex: "Male",
      sport: "Football",
      weight_lbs: "275",
      id: 213,
      age: 18,
      control_concussed: "Control",
      height: "6'3\"",
      date_of_testing: "11/21/19",
    },
    {
      studyid: "HU_Conc_111",
      sex: "Female",
      sport: "Basketball",
      weight_lbs: "180",
      id: 214,
      age: 18,
      control_concussed: "Concussed",
      height: "5'9\"",
      date_of_testing: "1/7/20",
    },
    {
      studyid: "HU_Conc_112",
      sex: "Female",
      sport: "Skiing",
      weight_lbs: "130",
      id: 215,
      age: -1,
      control_concussed: "Control",
      height: "5'8\"",
      date_of_testing: "2/7/20",
    },
    {
      studyid: "HU_Conc_113",
      sex: "Female",
      sport: "Softball",
      weight_lbs: "145",
      id: 216,
      age: 21,
      control_concussed: "Control",
      height: "5'7\"",
      date_of_testing: "2/12/20",
    },
    {
      studyid: "HU_Conc_114",
      sex: "Female",
      sport: "Ice Hockey",
      weight_lbs: "145",
      id: 217,
      age: 20,
      control_concussed: "Control",
      height: "5'6\"",
      date_of_testing: "2/25/20",
    },
  ],
}

export default data
