const data = {
  headers: [
    {
      id: "studyID",
      text: "Study ID",
    },
    {
      id: "sex",
      text: "Sex",
    },
    {
      id: "dob",
      text: "Date of Birth",
    },
    {
      id: "height",
      text: "Height",
    },
    {
      id: "weight",
      text: "Weight",
    },
    {
      id: "control",
      text: "Control",
    },
    {
      id: "date",
      text: "Scan Date",
    },
    {
      id: "sport",
      text: "Sport",
    },
  ],
  items: [
    {
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: "135",
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: "260",
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: "135",
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: "260",
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: "135",
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: "260",
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: "135",
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: "260",
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: "135",
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: "135",
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: "260",
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
  ],
}

export default data
