const data = {
  headers: [
    {
      id: "id",
      text: "#",
    },
    {
      id: "studyID",
      text: "Study ID",
    },
    {
      id: "sex",
      text: "Sex",
    },
    {
      id: "dob",
      text: "Date of Birth",
    },
    {
      id: "height",
      text: "Height",
    },
    {
      id: "weight",
      text: "Weight",
    },
    {
      id: "control",
      text: "Control",
    },
    {
      id: "date",
      text: "Scan Date",
    },
    {
      id: "sport",
      text: "Sport",
    },
  ],
  items: [
    {
      id: 1,
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      id: 2,
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      id: 3,
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: 135,
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      id: 4,
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      id: 5,
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: 260,
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      id: 6,
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      id: 7,
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      id: 8,
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: 135,
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      id: 9,
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      id: 10,
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: 260,
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      id: 11,
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      id: 12,
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      id: 13,
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: 135,
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      id: 14,
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      id: 15,
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: 260,
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      id: 16,
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      id: 17,
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      id: 18,
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: 135,
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      id: 19,
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      id: 20,
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: 260,
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
    {
      id: 21,
      studyID: "HU_BC_01",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/24/2020",
      sport: "Soccer",
    },
    {
      id: 22,
      studyID: "HU_BC_02",
      sex: "Female",
      dob: "7/24/2001",
      height: "5'7\"",
      weight: 135,
      control: "Yes",
      date: "1/17/2020",
      sport: "Soccer",
    },
    {
      id: 23,
      studyID: "HU_BC_03",
      sex: "Female",
      dob: "7/5/2001",
      height: "5'6\"",
      weight: 135,
      control: "Yes",
      date: "1/29/2020",
      sport: "Soccer",
    },
    {
      id: 24,
      studyID: "HU_BC_04",
      sex: "Male",
      dob: "",
      height: "",
      weight: "",
      control: "No",
      date: "1/31/2020",
      sport: "",
    },
    {
      id: 25,
      studyID: "HU_Conc_01",
      sex: "Male",
      dob: "5/28/2001",
      height: "6'3\"",
      weight: 260,
      control: "No",
      date: "11/5/2015",
      sport: "Football",
    },
  ],
}

export default data
